[package]
name = "attributes-info"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc_feature = { path = "rustc_feature" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
version_check = "0.9.4"

[workspace]
members = [
    "rustc_feature",
    "rustc_span",
    "rustc_data_structures",
    "rustc_macros",
    "rustc_attr_data_structures"
]
