name: milestones

on:
    pull_request_target:
        types: [ closed ]

jobs:
    set_milestone:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set milestone
              if: github.event.pull_request.merged && github.event.pull_request.milestone == null
              run: python scripts/set_milestone.py --token ${{ github.token }} --pull-request ${{ github.event.pull_request.number }}
