name: rust nightly

on:
    workflow_dispatch:
    schedule:
        - cron: '0 2 * * *'

jobs:
    generate-build-number:
        runs-on: ubuntu-latest
        outputs:
            build_number: ${{ steps.buildnumber.outputs.build_number }}
        steps:
            - name: Generate build number
              uses: einaregilsson/build-number@v3
              id: buildnumber
              with:
                  token: ${{ secrets.github_token }}
                  prefix: rust

    fetch-latest-changes:
        runs-on: ubuntu-latest
        outputs:
            rust-commit: ${{ steps.fetch-commits.outputs.rust-commit }}
            rust-nightly: ${{ steps.fetch-commits.outputs.rust-nightly }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Fetch latest commits
              id: fetch-commits
              run: |
                  echo "rust-commit=$(git log -n 1 --format=format:%H)" >> $GITHUB_OUTPUT
                  echo "rust-nightly=$(python scripts/get_tag_commit.py --tag "rust-nightly")" >> $GITHUB_OUTPUT

            - name: Show commits
              run: |
                  echo "rust-commit: ${{ steps.fetch-commits.outputs.rust-commit }}"
                  echo "rust-nightly: ${{ steps.fetch-commits.outputs.rust-nightly }}"


    build-native-code:
        if: needs.fetch-latest-changes.outputs.rust-commit != needs.fetch-latest-changes.outputs.rust-nightly
        needs: [ fetch-latest-changes ]
        uses: ./.github/workflows/build-native-code.yml
        with:
            rust-version: stable
            cache: false

    build:
        if: needs.fetch-latest-changes.outputs.rust-commit != needs.fetch-latest-changes.outputs.rust-nightly
        needs: [ generate-build-number, fetch-latest-changes, build-native-code ]
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                platform-version: [ 232 ]
        env:
            ORG_GRADLE_PROJECT_buildNumber: ${{ needs.generate-build-number.outputs.build_number }}
            ORG_GRADLE_PROJECT_platformVersion: ${{ matrix.platform-version }}
            ORG_GRADLE_PROJECT_enableBuildSearchableOptions: true
            ORG_GRADLE_PROJECT_publishChannel: nightly
            ORG_GRADLE_PROJECT_publishToken: ${{ secrets.plugin_bot_token }}
            ORG_GRADLE_PROJECT_compileNativeCode: false

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: corretto
                  java-version: 17

            - name: Load native binaries
              uses: ./.github/actions/load-native-binaries

            - name: Publish rust plugin
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: ":plugin:publishPlugin"
                  cache-disabled: true

    save-commit:
        needs: [ build, fetch-latest-changes ]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

            - name: Save commits
              run: |
                  python scripts/save_tag.py --tag rust-nightly --commit ${{ needs.fetch-latest-changes.outputs.rust-commit }}
